"""Writes include/bridger/lua/engine.d.lua: the engine, described for the Lua language server.

With the Lua extension for VS Code (sumneko / LuaLS) pointed at include/bridger/lua, every engine
class autocompletes its reflected fields with their types, every exported engine function its
parameters, every enum its values, and the strings hook() and on() take complete to real names.

    python tools/script/gen_luals.py

Reads data/rtti/ds/static.json (types) and data/rtti/ds/signatures.json (functions). The hand-written
half of the API lives beside the output, in bridger.d.lua.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TYPES = ROOT / "data/rtti/ds/static.json"
SIGNATURES = ROOT / "data/rtti/ds/signatures.json"
OUT = ROOT / "include/bridger/lua/engine.d.lua"

INTEGERS = {"int8", "uint8", "int16", "uint16", "int", "int32", "uint", "uint32", "int64", "uint64",
            "wchar", "tchar", "ucs4", "uintptr", "HalfFloat", "char", "short", "long"}
NUMBERS = {"float", "double"}
LUA_KEYWORDS = {"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if",
                "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while"}


def split_template(name):
    match = re.fullmatch(r"(\w+)<(.+)>", name)
    return (match.group(1), match.group(2)) if match else (None, None)


class Catalogue:
    def __init__(self, types):
        self.types = types
        self.classes = {n for n, t in types.items() if t["kind"] == "class"}
        self.enums = {n for n, t in types.items() if t["kind"].startswith("enum")}

    def field_type(self, name):
        name = name.strip()
        if name == "bool":
            return "boolean"
        if name in INTEGERS:
            return "integer"
        if name in NUMBERS:
            return "number"
        if name in ("String", "WString", "GGUUID"):
            return "string"
        outer, inner = split_template(name)
        if outer in ("Ref", "cptr", "WeakPtr"):
            return f"{inner}?" if inner in self.classes else "bridger.View?"
        if outer == "UUIDRef":
            return "string"
        if outer == "StreamingRef":
            return "integer"
        if outer == "Array":
            item = self.field_type(inner)
            return f"({item})[]" if "?" in item or "|" in item else f"{item}[]"
        if name in self.enums:
            return f"{name}"
        if name in self.classes:
            return name
        return "any"

    def parameter(self, token):
        """(annotation, is_out) for an exported function parameter token."""
        text = token.replace("*", " * ").replace("&", " & ")
        words = text.split()
        depth = words.count("*")
        reference = "&" in words
        const = "const" in words
        base = next((w for w in words if w not in ("*", "&", "const", "unsigned", "struct", "class")), "void")
        if depth == 0 and not reference:
            annotation = self.field_type(base)
            if base in self.classes and annotation == base:
                annotation = f"{base}|table"
            return annotation, False
        if base in ("char", "tchar") and depth == 1:
            return "string", False
        if base in self.classes:
            annotation = f"{base}|table|integer" if reference else f"{base}|integer?"
            return annotation, (not const and depth >= 1)
        if base == "void":
            return "integer|bridger.View?", False
        return f"{self.field_type(base)}|bridger.Out|integer", not const

    def result(self, token):
        text = token.replace("*", " * ").replace("&", " & ")
        words = text.split()
        base = next((w for w in words if w not in ("*", "&", "const", "unsigned")), "void")
        if base == "void" and "*" not in words:
            return None
        if "*" in words or "&" in words:
            if base in ("char", "tchar"):
                return "string?"
            return f"{base}?" if base in self.classes else "integer?"
        return self.field_type(base)


def identifier(text, used):
    snake = re.sub(r"(?<!^)(?=[A-Z][a-z])", "_", re.sub(r"\W", "", text)).lower() or "value"
    if snake[0].isdigit() or snake in LUA_KEYWORDS:
        snake = "_" + snake
    candidate, n = snake, 2
    while candidate in used:
        candidate, n = f"{snake}{n}", n + 1
    used.add(candidate)
    return candidate


def quote(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    types = json.loads(TYPES.read_text(encoding="utf-8"))["types"]
    signatures = json.loads(SIGNATURES.read_text(encoding="utf-8"))["signatures"]
    catalogue = Catalogue(types)
    out = ["---@meta", "-- Generated by tools/script/gen_luals.py from the RTTI database. Do not edit.", ""]

    out.append("---@class enum")
    for name in sorted(catalogue.enums):
        out.append(f"---@field {name} enum.{name}")
    out.append("")
    for name in sorted(catalogue.enums):
        out.append(f"---@alias {name} integer")
        out.append(f"---@class enum.{name}")
        for value in types[name].get("values", []):
            label = value.get("name") or ""
            if re.fullmatch(r"[A-Za-z_]\w*", label) and label not in LUA_KEYWORDS:
                out.append(f"---@field {label} integer {value['value']}")
        out.append("")

    for name in sorted(catalogue.classes):
        t = types[name]
        bases = [b["name"] for b in t.get("bases", []) if b["name"] in catalogue.classes]
        parents = ", ".join(bases) if bases else "bridger.View"
        out.append(f"---@class {name}: {parents}")
        seen = set()
        for member in t.get("members", []):
            field = member.get("name") or ""
            if field in seen or not member.get("type") or not re.fullmatch(r"[A-Za-z_]\w*", field):
                continue
            seen.add(field)
            note = f"+{member['offset']} {member['type']}" if not member.get("property") else f"property {member['type']}"
            out.append(f"---@field {field} {catalogue.field_type(member['type'])} {note}")
        out.append("")

    out.append("---@alias bridger.Symbol")
    for key in sorted(signatures):
        out.append(f"---| {quote(key)}")
    out.append("")
    out.append("---@alias bridger.Message")
    for name in sorted(n for n in catalogue.classes if n.startswith("Msg")):
        out.append(f"---| {quote(name)}")
    out.append("")
    out.append("---@alias bridger.HandlerClass")
    for name in sorted(n for n in catalogue.classes if types[n].get("message_handlers")):
        out.append(f"---| {quote(name)}")
    out.append("")

    groups = {}
    for key, tokens in signatures.items():
        group, function = key.split("::", 1)
        groups.setdefault(group, []).append((function, tokens))
    out.append("---@class engine")
    out.append("---@field find fun(pattern: string, limit?: integer): string[]")
    out.append("---@field groups fun(): string[]")
    for group in sorted(groups):
        out.append(f"---@field {group} engine.{group}")
    out.append("engine = {}")
    out.append("")
    for group in sorted(groups):
        out.append(f"---@class engine.{group}")
        out.append("---@field list fun(): string[]")
        for function, tokens in sorted(groups[group]):
            if not re.fullmatch(r"[A-Za-z_]\w*", function):
                continue
            params = []
            used = set()
            for token in tokens[1:]:
                annotation, is_out = catalogue.parameter(token)
                base = token.replace("const", "").replace("*", "").replace("&", "").strip() or "value"
                if base in INTEGERS or base in NUMBERS:
                    base = "out" if is_out else "value"
                elif base == "bool":
                    base = "out" if is_out else "flag"
                params.append((identifier(base, used), annotation, token, is_out))
            result = catalogue.result(tokens[0])
            signature = f"{tokens[0]} {function}({', '.join(tokens[1:])})"
            out.append(f"---@field {function} fun({', '.join(f'{n}: {a}' for n, a, _, _ in params)})"
                       + (f": {result}" if result else "")
                       + f" {signature}")
        out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    size = OUT.stat().st_size / 1024 / 1024
    print(f"wrote {OUT.relative_to(ROOT)}: {len(catalogue.classes)} classes, {len(catalogue.enums)} enums, "
          f"{len(signatures)} functions ({size:.1f} MiB)")


if __name__ == "__main__":
    main()
